name: Run Kworb Spotify Scraper

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      # ESTO NOS VA A DECIR LA VERDAD: Ver qué archivos hay realmente en el servidor
      - name: Depurar y listar archivos
        run: ls -la

      - name: Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerias
        run: pip install requests beautifulsoup4 supabase lxml

      - name: Ejecutar Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scraper.py
